theme: jekyll-theme-minimal
title: Coup History Lessons
description: Learn how militaries of other countries staged their coups and gain power for the long term, and how other people protest against them.